#cloud-config


package_update: true

packages:
  - mysql-server

runcmd:
  - systemctl enable mysql
  - systemctl start mysql
  - sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf
  - systemctl restart mysql
  - |
    ROOT_PASSWORD=${mysql_root_password}
    FINAL_PASSWORD=${mysql_final_password}
    mysql --defaults-file=/etc/mysql/debian.cnf -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '$ROOT_PASSWORD';"
    mysql --defaults-file=/etc/mysql/debian.cnf -e "CREATE DATABASE IF NOT EXISTS final_db;"
    mysql --defaults-file=/etc/mysql/debian.cnf -e "CREATE USER IF NOT EXISTS 'final'@'%' IDENTIFIED BY '$FINAL_PASSWORD';"
    mysql --defaults-file=/etc/mysql/debian.cnf -e "ALTER USER 'final'@'%' IDENTIFIED BY '$FINAL_PASSWORD';"
    mysql --defaults-file=/etc/mysql/debian.cnf -e "GRANT ALL PRIVILEGES ON final_db.* TO 'final'@'%';"
    mysql --defaults-file=/etc/mysql/debian.cnf -e "FLUSH PRIVILEGES;"
    mysql --defaults-file=/etc/mysql/debian.cnf -e "USE final_db; CREATE TABLE IF NOT EXISTS requests (id INT AUTO_INCREMENT PRIMARY KEY, ip VARCHAR(45) NOT NULL, time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);"
